### ISSUE TITLE
Introduce what modules are and why module detection is important

### ISSUE THREAD

**Issue by erictleung** [greenstick/neo4j-tutorial#1]
- Modules: https://en.wikipedia.org/wiki/Modularity_(networks)
- Scientific rationale of challenge: https://www.synapse.org/#!Synapse:syn6156761/wiki/400650

Algorithm Detection Methods
- "Community detection in graphs" http://www.sciencedirect.com/science/article/pii/S0370157309002841
- "Comparison of module detection algorithms in protein networks and investigation of the biological meaning of predicted modules" https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0979-8

**Comment by greenstick** [comment]
I'm thinking I'm going to skip over this and dive right into the code for the tutorial. Are there any things in this vein that you think should be covered (I'm assuming a bit of this is discussed in the presentation)? 

For now I'm planning on graphing out the degrees of the network to see how well it follows a power law distribution, maybe run a few centrality algorithms, then run a module detection algorithm (all this with NetworkX.)

**Comment by erictleung** [comment]
@greenstick no worries. I think the content of this issue is covered in this commit https://github.com/greenstick/neo4j-tutorial/commit/dff7cefd4ab34bee860dde513fa0277fd517a6b6. Let us know if you have any issues with coding stuff.
